### ISSUE TITLE
Error in 3.1.0 version

### ISSUE THREAD

**Issue by antonzax36** [Neltulz/Neltulz_Smart_Frame_Selection#1]
Error when I try to zoom all the objects in the scene ^_^

Screenshot: [Link](https://drive.google.com/file/d/1qDYHr_PA-CHblD8Q4Q5yd9gSbgopPphl/view?usp=sharing)

The code:
`Python: Traceback (most recent call last):
  File "C:\Users\antonzax36\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Neltulz_Smart_Frame_Selection-master\mainOt.py", line 582, in invoke
    return self.execute(context)
  File "C:\Users\antonzax36\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Neltulz_Smart_Frame_Selection-master\mainOt.py", line 576, in execute
    _execute(self, context)
  File "C:\Users\antonzax36\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Neltulz_Smart_Frame_Selection-master\mainOt.py", line 266, in _execute
    miscFunc.viewAll(self, context, scene, addonPrefs, modeAtBegin, bUseAllRegions, bUseAll3DAreas)
  File "C:\Users\antonzax36\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Neltulz_Smart_Frame_Selection-master\miscFunc.py", line 405, in viewAll
    obj.select_set(True)
RuntimeError: Error: Object 'Cube' can't be selected because it is not in View Layer 'ViewLayer'!

location: <unknown location>:-1

`

**Comment by Neltulz** [comment]
Sorry, I haven't been active with Blender for quite some time now.  If somebody would like to fork this extension and fix the bugs related to it, you're more than welcome to since I have a lot on my plate right now and won't be able to fix this for a couple of months.
